#!/bin/sh
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 2/Packages

# symlink settings in
echo "Installing Sublime Text 2 preferences..."
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$HOME/.dotfiles/sublime/User" "$sublime_dir"

# Grab the Soda theme
soda_dir=Theme\ -\ Soda
echo "Fetching Soda Theme interface..."
cd "$sublime_dir"
if [ ! -d "$soda_dir" ]; then
  git clone https://github.com/buymeasoda/soda-theme/ "$soda_dir"
else
  cd "$soda_dir"
  git pull
fi
echo "Sublime Text 2 installation complete."
