#!/usr/bin/env zsh

## Docs https://thoughtbot.github.io/rcm/rcrc.5.html
EXCLUDES="README.md LICENSE TODO.md bin resources script wip homebrew"
SYMLINK_DIRS="config conda claude"
UNDOTTED="Brewfile AGENTS.md"
