#!/usr/bin/env zsh

export DOTFILES="$HOME/.dotfiles"
export TOOLSHED="$HOME/code/toolshed"

echo "Ensuring $DOTFILES/script and $TOOLSHED/{bin,wip} are executable..."

chmod +x $DOTFILES/script/*
chmod +x $TOOLSHED/bin/* $TOOLSHED/wip/*
