[tools]
node = "latest"
ruby = "latest"
python = "latest"
rust = "latest"
go = "latest"
bun = "latest"
pipx = "latest"
npm = "latest"
uv = "latest"
zig = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false

[shell_alias]
m = "mise"
a = "ansible"
ap = "ansible-playbook"
