alias sz='source ~/.zshrc'
alias ss='script/server'
alias sc='script/console'
alias rr='script/replicate-repo'
alias j='jekyll serve --watch'
alias y='yeoman'
alias be='bundle exec'
alias ghgh='cd ~/github/github'
alias gh='github'
alias tu="cd ~/code/trotup"
alias updatedb='sudo /usr/libexec/locate.updatedb'
alias rake="noglob rake"
alias ta="tmux -u attach"
alias tx="tmux -u"
alias ia="open $1 -a /Applications/iA\ Writer.app"
alias wp="open $1 -a /Applications/Writer\ Pro.app"
