alias sz='source ~/.zshrc'
alias ss='script/server'
alias sc='script/console'
alias rr='script/replicate-repo'
alias j='jekyll'
alias js='jekyll --server --auto --url http://localhost:4000'
alias y='yeoman'
